### PR TITLE
Update 3D Objects metadatablock's Material Composition field

### LINKED ISSUE #163: Let depositors of datasets in the Boston College Dataverse collection enter any text into the custom 3D Objects metadata block's Material Composition field
The Material Composition field in the custom 3D Objects metadata block lets depositor choose only one material from the field's controlled vocabulary.

The administrators of the Boston College Dataverse collection asked that we change the Material Composition field so that depositors can type in a material in a text box and so that they can enter multiple materials (change the field's allowMultiple property to TRUE).

I created a PR at https://github.com/IQSS/dataverse.harvard.edu/pull/164 that edits the TSV file.

Then it looks like the curl command in the Admin Guide's section about [reloading a metadatablock](https://guides.dataverse.org/en/5.10.1/admin/metadatacustomization.html#reloading-a-metadata-block) will need to be run to apply the change, such as `curl http://localhost:8080/api/admin/datasetfield/load -H "Content-type: text/tab-separated-values" -X POST --upload-file custom3d.tsv`

Does anything else need to be done to apply the change?

### PR DESCRIPTION
**Pull request by jggautier**
Closes #163

Changing allowMultiples property of 3dMaterialComposition field from FALSE to TRUE so that depositors can choose multiple materials from the fields controlled vocabulary.

### CODE REVIEW

**Comment by jggautier** [comment]
The collection administrators just asked me to revise this request to make the field a free text field that allows multiple values, so I'll be updating the TSV file in this PR.

**Review by pdurbin — APPROVED** [review]
Looks good. Material Composition is multivalued and is free text rather than being a controlled vocabulary. Here's a screenshot:

Screen Shot 2022-07-28 at 11 20 54 AM

**Comment by kcondon** [comment]
OK, looks good. Passing to @landreev to apply to prod, thanks!

**Comment by jggautier** [comment]
Hey @landreev. There's still no rush on this, but could we estimate when this metadata field will be changed? I'd like to give the collection admins an update if possible.

**Comment by landreev** [comment]
Will apply this to prod. tonight after hours.

**Comment by landreev** [comment]
OK, done. Apologies for the confusion and delay with this.

**Comment by jggautier** [comment]
Hey @landreev. When you wrote done, did you mean that the Materials Composition metadata field should be changed now from a dropdown menu to a text box that depositors can create multiple instances of?

I ask because when I edited a dataset in the collection at https://dataverse.harvard.edu/dataverse/bc3d, the Materials Composition field was still a dropdown (where multiple values from a controlled vocabulary can be chosen) instead of a text box where I could create multiple instances of that text box. Maybe there's a delay for then the field will be changed?

I double checked the TSV and .properties files in this pull request and in this repo's "metadatablocks" folder at https://github.com/IQSS/dataverse.harvard.edu/tree/master/metadatablocks and it all looks good.

**Comment by landreev** [comment]
Sorry, I don't think I'm getting github notifications for this repo. Feel free to ping me directly on slack with things like this. 
I'm not sure what's going on. The updated block is definitely installed in prod. Did the dataset you were looking at had that metadata field already populated with a controlled vocab. value? - Maybe updating the block does not have any effect for cases like that? OK, let me investigate.

**Comment by landreev** [comment]
This may be a bug in our metadata block update code. The `allowcontrolledvocabulary` is set to false for this field now; but the actual controlled vocab. entries are still there and tied to the field. And that's why the page is showing it as a dropdown. I'm not sure what the update was supposed to do; it could try to remove these controlled vocab. values, but that would not work if there were any existing fields using them. I guess it needs to remove the fields too? Otherwise it's not clear how the metadata edit page is supposed to behave. 
Anyway, I need to ask other devs. about this.

**Comment by landreev** [comment]
OK, manually deleting the old Controlled Vocab. values that used to be associated with the field; and now it's showing as it should be, as a textbox, with a plus button. 
I'm assuming we want a dev. issue, to address the update behavior (what should it do exactly, in a situation when there ARE field using the controlled vocab. values??)

**Comment by jggautier** [comment]
Thanks @landreev. When I edit an existing dataset in the collection or create a new dataset in the collection, the Material Composition field is a free text field that allows multiple values (with the plus button).

I'll let the admins know the field has been changed.

**Comment by landreev** [comment]
Dev. issue for the update behavior: https://github.com/IQSS/dataverse/issues/8997
dragging this back into "done".

**Pull request merged**
