### PR TITLE
Add datacite-badge to footer

### LINKED ISSUE #210: Add Badge for DataCite registration provider
We recently re registered Harvard Dataverse as a DataCite service provider for 2023 and they sent us a badge. Stefano suggested adding it to the site, and Julian suggested on the home page footer. (Details to be worked out with Julian)

This zip contains what they sent:
[datacite_service_provider_badge.zip](https://github.com/IQSS/dataverse.harvard.edu/files/10512502/datacite_service_provider_badge.zip)

The zip contains the badge in two different colors and two different formats (png and svg):

### PR DESCRIPTION
**Pull request by jp-tosca**
**What this PR does / why we need it**:

> Request to add provided DataCite badge to the custom footer.

**Which issue(s) this PR closes**:

- Closes #210 

**Special notes for your reviewer**:

> I meet with @jggautier to discuss sizing, location and behavior. ARIA and accessibility tags were created. 

**Suggestions on how to test this**:

> Create a Dataverse installation and customize the footer.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

image

### CODE REVIEW

**Comment by jggautier** [comment]
Or the link could go to the page at    https://datacite.org/service-providers about DataCite Service Providers. If people clicked on the badge, that page seems more relevant to me

**Comment by jp-tosca** [comment]
Added https://datacite.org/service-providers as the link @jggautier @pdurbin

**Comment by jggautier** [comment]
Thanks, yeah I think clicking the image should open the page in a new tab 👍

**Comment by jp-tosca** [comment]
Now the link will open in a separate tab just as the feedback link 😄

**Comment by jggautier** [comment]
I'm gonna remove myself from this PR. I asked in Slack about Harvard Dataverse being listed as a service provider on the DataCite page, and I'll follow up next Monday.

To be honest, the description of a service provider makes me wonder if Harvard Dataverse really is one or if it's only Dataverse that is. Maybe the badge should be on Dataverse.org and not on Harvard Dataverse after all. Or maybe I don't understand the intention behind adding the badge to Harvard Dataverse.

**Comment by pdurbin** [comment]
@jggautier yeah, maybe you're right. Maybe the badge should go on dataverse.org.

Here's a screenshot from https://datacite.org/service-providers/ of what we're talking about:

Screenshot 2023-12-11 at 09-12-00 DataCite Registered Service Providers - DataCite

I'm going to assign this to @siacus and @scolapasta for a decision.

**Comment by pdurbin** [comment]
https://datacite.org/service-providers/ is the correct link. Dataverse, the software is correctly, listed there.

**Comment by jp-tosca** [comment]
> https://datacite.org/service-providers/ is the correct link. Dataverse, the software is correctly, listed there.

I double checked the code and this is the link that we are using for the badge 😃

**Comment by pdurbin** [comment]
Sure, but do we want the badge on https://dataverse.harvard.edu (this PR) or https://dataverse.org ?

(A third option is to add it to the footer of Dataverse itself but that probably doesn't make sense because some installations mint PIDs using Handles or Permalinks instead of DOIs from DataCite.)

**Comment by pdurbin** [comment]
Badge should be on both according to Stefano, per JP.

**Comment by jp-tosca** [comment]
https://github.com/IQSS/dataverse/issues/10213 Was open to address the second part of this request.

**Review by pdurbin — APPROVED** [review]
Clicking the image now opens the link in a new tab. Approved.

**Comment by pdurbin** [comment]
@scolapasta @jp-tosca when this PR is merged, it'll close the only issue in the sprint. If you want follow up issues on the board or in the sprint, please add them.

**Comment by jp-tosca** [comment]
We talked on standup on "1/10/2024" and @scolapasta mentioned that it would be good when this goes through QA should be followed with the deployment.

**Comment by landreev** [comment]
OK, installed in prod. Merging the PR.

**Pull request merged**
