### PR TITLE
Added newly updated customization files to github repo [ref #94]

### PR DESCRIPTION
**Pull request by mheppler**
Rather than relying on Google Drive to keep track of these customization files, we will store them here in the dataverse.harvard.edu GitHub repo.

In addition to adding these files to the repo, there was also a minor update to the homepage customization to resolve a minor CSS related layout issue where the "Find" button text label wraps under the magnifying glass icon in the search input-group button. The text label was removed from the button and added to a Bootstrap tooltip which displays on hover.

Screen Shot 2021-02-09 at 11 37 54 AM

### CODE REVIEW

**Review by pdurbin — COMMENTED** [review]
I'm just curious if we should continue to maintain custom-homepage-dynamic.html in the guides. Perhaps we could link here instead. Or keep it. No strong opinion. Here's the blurb from https://guides.dataverse.org/en/5.3/installation/config.html#custom-homepage

> If you prefer to start with less of a blank slate, you can download the custom-homepage-dynamic.html template which was built for the Harvard Dataverse, and includes branding messaging, action buttons, search input, subject links, and recent dataset links. This page was built to utilize the Metrics API to deliver dynamic content to the page via javascript.

**Comment by scolapasta** [comment]
> I'm just curious if we should continue to maintain custom-homepage-dynamic.html in the guides. Perhaps we could link here instead. Or keep it. No strong opinion. Here's the blurb from https://guides.dataverse.org/en/5.3/installation/config.html#custom-homepage
> 
> > If you prefer to start with less of a blank slate, you can download the custom-homepage-dynamic.html template which was built for the Harvard Dataverse, and includes branding messaging, action buttons, search input, subject links, and recent dataset links. This page was built to utilize the Metrics API to deliver dynamic content to the page via javascript.

I guess it depends on if we make this repo private or not. (there had been talk that we may need to do that). If it's public pointing to here makes complete sense. @djbrooke thoughts on if we will make this repo private?

**Comment by djbrooke** [comment]
@scolapasta thanks for mention. We'll keep this repo public for the foreseeable future. If we add some security-related or other non-shareable code in the future that's not appropriate for the wider audience in dataverse-security we could add dataverse.harvard.edu-security, but I don't have a use case for this right now.

**Comment by mheppler** [comment]
> I'm just curious if we should continue to maintain custom-homepage-dynamic.html in the guides. Perhaps we could link here instead.

@pdurbin the reason for the two different version is that the one in the guides is meant to be generic, a starting point, and this one in the Harvard is an exact copy of the latest and greatest that is on production. It has already been updated from the original generic version with new content and links that are specific to Harvard's content.

**Review by djbrooke — APPROVED** [review]
I'm going to approve this, as this reflects an improvement over Google Drive and matches how I envisioned the iqss/dataverse.harvard.edu repo being used

**Pull request merged**
