### PR TITLE
Edit customNDR metadatablock's Study Design fields

### LINKED ISSUE #166: Edit customNDR metadatablock to correct metadatablock name, remove Study Design field, and make its child fields primitive fields
Managers of the [The Negotiation Data Repository](https://dataverse.harvard.edu/dataverse/NegotiationDataRepository) asked for the recently added customNDR metadatablock, the four child fields of the "Study Design" field be their own fields, instead, in order to prevent the design problem described at https://github.com/IQSS/dataverse/issues/6589.

So instead of:

<kbd>168840986-fadb82c7-0cdc-4ff0-ba3e-d540abcd04fa</kbd>

The "Study Design" field should be removed and the Protocol, Sample Size, Randomization, and Outcomes fields will be simple fields:

<kbd>Untitled-1</kbd>

I can make a PR in this repository with the edited TSV and properties files. 

Because there's a published dataset at https://doi.org/10.7910/DVN/ZZG2FE with values in these fields, @scolapasta or other developer colleagues, will anything else need to be done for for this dataset? The database names of the four fields aren't changing, so no database edits are needed to move the metadata values in that published dataset, right?

### PR DESCRIPTION
**Pull request by jggautier**
Closes #166

This PR removes the Study Design parent field and makes its child fields their own primitive fields.

It also corrects the name of the metadatablock (from customNRD to customNDR) in the TSV and properties files.

There's at least one published dataset, at https://doi.org/10.7910/DVN/ZZG2FE, that has those metadata fields filled in.

### CODE REVIEW

**Comment by pdurbin** [comment]
At standup we agreed that after we merge this PR we should create a new issue to track the work of changing the database in production (the block is being renamed from "customNRD" to "customNDR").

**Review by sekmiller — APPROVED** [review]

**Comment by kcondon** [comment]
fwiw, the steps to apply as I understand them:
1. copy over the customNDR.properties file to the right place on your system
3. update the db to rename the old custom block
4. load new custom block
5. update solr schema.xml, using update script procedure (haven't yet confirmed this is needed)

**Comment by sekmiller** [comment]
Steps for updating

1) update metadata block name:

update metadatablock set name = 'customNDR' 
where displayname = 'Negotiation Data Repository Metadata';

2) reload block:

curl http://localhost:8080/api/admin/datasetfield/load -H "Content-type: text/tab-separated-values" -X POST --upload-file customNDR.tsv

3) get the dataset version from compound field:

select datasetversion_id from datasetfield where id =(
select parentdatasetfield_id from datasetfieldcompoundvalue where id =
(select distinct parentdatasetfieldcompoundvalue_id from datasetfield where datasetfieldtype_id in (
	select id from datasetfieldtype where name in(
'nrdStudyProtocol',
'nrdStudyDesignSampleSize',
'nrdStudyDesignRandomization',
'nrdStudyDesignOutcomes')
)))

4) update the value of formerly child fields to get them to display:

update  datasetfield  set datasetversion_id = XXX-Result from query 3 where datasetfieldtype_id in (
	select id from datasetfieldtype where name in(
'nrdStudyProtocol',
'nrdStudyDesignSampleSize',
'nrdStudyDesignRandomization',
'nrdStudyDesignOutcomes')
)


5) remove the unused parent dataset field type:

update datasetfield set parentdatasetfieldcompoundvalue_id = null where datasetfieldtype_id in (
	select id from datasetfieldtype where name in(
'nrdStudyProtocol',
'nrdStudyDesignSampleSize',
'nrdStudyDesignRandomization',
'nrdStudyDesignOutcomes’));

6) update display order (if unable to delete Study design parent type) :

update datasetfieldtype set displayorder = displayorder+1  where metadatablock_id = 10
and displayorder > 4 and name != 'nrdStudyDesign';

**Comment by sekmiller** [comment]
Here are the steps required to update the Metadata Block (It has been tested with my local DB for one Dataverse having two templates, a published dataset and a draft version of the published dataset.):

Steps for updating NDR metadata block

1) update metadata block name:

update metadatablock set name = 'customNDR' 
where displayname = 'Negotiation Data Repository Metadata';

2) reload block with the corrected fields:

curl http://localhost:8080/api/admin/datasetfield/load -H "Content-type: text/tab-separated-values" -X POST --upload-file customNDR.tsv

3) run this to get a table for running the update query in step 4:

select * from datasetfield where id in (
select parentdatasetfield_id from datasetfieldcompoundvalue where id in
(select  parentdatasetfieldcompoundvalue_id from datasetfield where datasetfieldtype_id in (
	select id from datasetfieldtype where name in(
'nrdStudyProtocol',
'nrdStudyDesignSampleSize',
'nrdStudyDesignRandomization',
'nrdStudyDesignOutcomes')
)));

The results will look something like this(one row for each dataset version or template that has values from the NDR metadata block):
parentdatasetfieldcompoundvalue_id template_id datasetversion.id
2186	null	390
2192	null	391
2177	72	null
2151	71	null


4) update the value of formerly child fields to get them to display(replace the values with those from the above query - there will be one row - one update query for each dataset version or template that uses the metadata block):

update  datasetfield  set datasetversion_id = [value from column 3],
template_id = [value from column 2]
where parentdatasetfieldcompoundvalue_id = [value from column 1];


5) remove the unused parent dataset field type:

update datasetfield set parentdatasetfieldcompoundvalue_id = null where datasetfieldtype_id in (
	select id from datasetfieldtype where name in(
'nrdStudyProtocol',
'nrdStudyDesignSampleSize',
'nrdStudyDesignRandomization',
'nrdStudyDesignOutcomes'));

6) delete Study design parent type(3 separate delete queries):

delete from datasetfieldcompoundvalue 
where parentdatasetfield_id
in (select id from datasetfield where datasetfieldtype_id
in (select Id from datasetfieldtype where name ='nrdStudyDesign'));
	
delete from datasetfield where datasetfieldtype_id 	
in (select Id from datasetfieldtype where name ='nrdStudyDesign');	

delete from datasetfieldtype where name ='nrdStudyDesign';

**Comment by kcondon** [comment]
@jggautier @sekmiller wrote that fix to the order. I believe it is in v5.11 and has yet to be applied to prod.

**Pull request merged**
