### PR TITLE
Adding metadatablock files for The Negotiation Data Repository

### LINKED ISSUE #145: Add metadatablock for the Dataverse Collection: The Negotiation Data Repository
I'm working with administrators of the Dataverse collection, The Negotiation Data Repository, to add a custom metadatablock for their datasets.

### PR DESCRIPTION
**Pull request by jggautier**
Closes #145

Adds the metadatablock TSV properties files to this GitHub repository's "metadatablocks" directory.

Note the block expects a dataverse collection with alias 'NegotiationDataRepository' to exist. (on prod: https://dataverse.harvard.edu/dataverse/NegotiationDataRepository )

For this to be done, after QA, to sanity check the block, the last step is to load into production.

### CODE REVIEW

**Comment by scolapasta** [comment]
Looks fine. One thought I have is about the setup script (it's not part of this PR it just loads all). If the dv's don't exist it puts them at root. So I wonder if we should somehow have the script first add the dv's. Of course it would have to know what to give them for an alias in some way.... (this might be out of scope for this issue). Thoughts @jggautier @pdurbin ?

**Comment by jggautier** [comment]
Hey @scolapasta. I'm not too sure what the setup script does. Would this be how the metadatablock is added to a "production" server, like the Harvard Dataverse Repository? If so, so far whenever I've been involved in a creating a metadatablock for only one collection, the collection's already created. But I think your idea wouldn't hurt.

If it's for testing/QA, I think your idea sounds helpful. I think that when @kcondon was testing, the fact that a collection with the right alias wasn't already created in the test server he was using was a bit of a hiccup.

**Comment by scolapasta** [comment]
I do think we should change the code so that if a tsv file lists a dv alias and it is not found, the upload fails. That can be a separate issue that I will open: https://github.com/IQSS/dataverse/issues/8675

**Review by scolapasta — APPROVED** [review]

**Comment by kcondon** [comment]
looks good, ready for deployment

**Pull request merged**
