### PR TITLE
add custom3d metadata block, setup-harvard script, README update

### LINKED ISSUE #144: Add metadatablock for 3D data for Boston College
I'm working with librarians from Boston College to add a custom metadatablock that can be used to describe the 3D data they're depositing in a collection in the Harvard Dataverse Repository.

### PR DESCRIPTION
**Pull request by pdurbin**
- closes #144 

3D Objects Metadata block looks good to me:

Screen Shot 2022-04-14 at 2 38 27 PM

I used the custom3d files in the zip that @jggautier provided at https://github.com/IQSS/dataverse.harvard.edu/issues/144#issuecomment-1061222055

I also stubbed out a setup-harvard script and updated the README.

I marked this pull request to close the issue like we usually do but perhaps we should close it manually after all the QA and prod steps are done? I also removed the issue from the board, like usual.

### CODE REVIEW

**Comment by jggautier** [comment]
Thanks @pdurbin.

The screenshot matches what I and the collection admins saw when they reviewed the metadatablock on an AWS instance last month. So it looks good to go.

Should I create another AWS instance based on this branch and double check?

And is there anything I can do to help with the process for adding custom metadatablocks?

**Comment by scolapasta** [comment]
I went ahead and approved and moved to QA. @kcondon if you need @jggautier to double check anything while you're testing / adding block to prod, let us know.

**Review by scolapasta — APPROVED** [review]

**Comment by kcondon** [comment]
What I did to apply and test this:
1. Locate citation.properties, copy the new custom3d.properties file there (/usr/local/payara5/glassfish/domains/domain1/applications/dataverse-5.10.1/WEB-INF/classes/propertyFiles)
2. Apply tsv file using endpoint: curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary @custom3d.tsv -H "Content-type: text/tab-separated-values"
3. Restart payara
4. Update schema.xml: cd /usr/local/solr/solr-8.11.1/server/solr/collection1/conf , back up schema.xml , update script: wget

**Comment by landreev** [comment]
OK, I'll apply it to prod.

**Comment by landreev** [comment]
OK, the block has been enabled in prod.

**Pull request merged**
